apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: transform-montreal
description: main application pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: [dev]
 - targetId: prod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: Cloud Run development service
run:
 location: projects/{{PROJECT_ID}}/locations/{{LOCATION}}
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: Cloud Run production service
run:
 location: projects/{{PROJECT_ID}}/locations/{{LOCATION}}